config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :products

  devise_for :users
  
  devise_scope :user do
  	root to: 'devise/sessions#new'  
  	#resources :users
  	get '/users/list', to: 'users#index', as: 'users/list'
    get 'item' => 'items#show', via: [:get, :post]
   resource :items


    resources :users
  end

  resources :activities

  match 'home' => 'home#index', via: 'get'
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  accepts_nested_attributes_for :items, allow_destroy: true

  validates :name, presence: true
  validates :total, presence: true

  include PublicActivity::Model  
  tracked owner: ->(controller, model) { controller && controller.current_user}

  def subtotals  
    self.items.map { |i| i.subtotal }  
  end  
  
  def total_all  
    subtotals.sum  
  end  
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /rents
  # GET /rents.json
  def index
    @rents = Rent.all
  end

  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    @rent = Rent.new
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new(rent_params)
    @rent.user_id = current_user.id
    @rent.total = @rent.total_all

    respond_to do |format|
      if @rent.save
        format.html { redirect_to @rent, notice: 'Rent was successfully created.' }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_params
      params.require(:rent).permit(:name, items_attributes: [:id,:product_id, :price,:quantity,:total,:_destroy])
    end
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<head>   
  <title>Rent</title>   
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
  <%= csrf_meta_tags %>   
</head>
<body>
  <div id="form">

  </div>
</body>

<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="light-well">
        <h2 class="page-header text-center">New Rent</h2>

          <%= form_with(model: rent, local: true) do |form| %>
          <% if rent.errors.any? %>
            <div id="my-error">
          <ul>
          <% rent.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control', id: :rent_name %>
          </div>

          <%= form.fields_for :items do |builder| %>   
            <%= render 'item_fields', f: builder %>   
          <% end %>   
          <%= link_to_add_fields "Add Item", form, :items %>  

          <div class="actions">
            <%= form.submit %>
          </div>
        <% end %>

      </div>
      <br>
      <br>
    </div>
  </div>
</div>


<script type="text/javascript">   
  jQuery(function() {   
   $('form').on('click', '.remove_fields', function(event) {   
   $(this).prev('input[type=hidden]').val('1');   
   $(this).closest('fieldset').hide();   
   return event.preventDefault();   
   });   
   return $('form').on('click', '.add_fields', function(event) {   
   var regexp, time;   
   time = new Date().getTime();   
   regexp = new RegExp($(this).data('id'), 'g');   
   $(this).before($(this).data('fields').replace(regexp, time));   
   return event.preventDefault();   
   });   
  });   
  </script>

app/views/rents/_item_fields.html.erb
<table>
  <tr>
    <td>Produtct: <%= f.collection_select :product_id, Product.all, :id, :name %>  </td>
    <td>Quantity: <%= f.text_field :quantity%>  </td>
    <td> <%= f.hidden_field :_destroy %>  
  </tr>
</table>

app/views/rents/edit.html.erb
<h1>Editing Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

app/views/rents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rents</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <td ><b>Name</b></td>
      <td><b>Total</b></td>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.name %></td>
        <td><%= rent.total %></td>
        <td><%= link_to 'Show', rent %></td>
        <% if can? :edit, Rent %>
          <td><%= link_to 'Edit', edit_rent_path(rent) %></td>
        <%end%>
        <% if can? :destroy, Rent %>
          <td><%= link_to 'Destroy', rent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rent', new_rent_path, :class => 'btn btn-info' %>

app/views/rents/new.html.erb
<%= render 'form', rent: @rent %>
<%= link_to 'Cancel', rents_path %>

app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>  
 <p>
 <%= link_to 'Back', rents_path %>  
 </p>

 <p>  
  <strong>Name:</strong>  
  <%= @rent.name %>  
 </p>  
 <p>
   <strong>User:</strong>
   <%= @rent.user.username %>
  </p>
 
 <h1>Listing Item</h1>  
 <table class="table table-striped">  
  <thead>  
   <tr>  
    <td><b>Product</b></td>  
    <td><b>Price</b></td>  
    <td><b>Quantity</b></td>  
    <td><b>Total</b></td>  
    <th></th>  
   </tr>  
  </thead>  
  <tbody>  
   <% @rent.items.each do |item| %>  
    <tr>  
     <td><%= item.product.name %></td>  
     <td><%= item.product.price %></td>  
     <td><%= item.quantity %></td>  
     <td><%= item.total %></td>  
    </tr>  
   <% end %>  
  </tbody>  
 </table>  
 <hr>  
  <p> Total </p>  
  <%= @rent.total%>  
 <hr>