config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :products

  devise_for :users
  
  devise_scope :user do
  	root to: 'devise/sessions#new'  
  	#resources :users
  	get '/users/list', to: 'users#index', as: 'users/list'
    get 'item' => 'items#show', via: [:get, :post]
   resource :items


    resources :users
  end

  resources :activities

  match 'home' => 'home#index', via: 'get'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  before_create :set_code  
  
  def generate_code(size = 6)  
   charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}  
   (0...size).map{ charset.to_a[rand(charset.size)] }.join  
  end  
  
  def set_code  
   self.code = generate_code(6)  
  end

  validates :name, presence: true
  validates :price, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :name, :price, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<head>   
  <title>Sale</title>   
  <%= stylesheet_link_tag "custom-devise", media: "all", "data-turbolinks-track" => true %>   
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
  <%= csrf_meta_tags %>   
</head>
<body>
  <div id="form">
  <%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="my-error">
      <!--<h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>-->

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control', id: :product_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</body>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <td><b>Code<b></td>
      <td><b>Name</b></td>
      <td><b>Price</b></td>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.code %></td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <% if can? :edit, Product %>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <%end%>
        <% if can? :destroy, Product %>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Product %>
  <%= link_to 'New Product', new_product_path, :class => 'btn btn-info' %>
<%end%>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>