config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :products

  devise_for :users
  
  devise_scope :user do
  	root to: 'devise/sessions#new'  
  	#resources :users
  	get '/users/list', to: 'users#index', as: 'users/list'
    get 'item' => 'items#show', via: [:get, :post]
   resource :items


    resources :users
  end

  resources :activities

  match 'home' => 'home#index', via: 'get'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>   
  <html>   
  <head>   
    <title>Admin Capital</title>   
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
    <%= csrf_meta_tags %>   
  </head>   
  <body>   
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">   
       <div class="container">   
         <div class="navbar-header"> 
            
            <% if user_signed_in? %>   
              <a class="navbar-brand" <%= link_to "Admin Capital", home_path %></a>             
            <% else %>   
              <a class="navbar-brand" <%= link_to "Admin Capital", root_path %></a> 
            <% end %>

         </div>   
         <ul class="nav navbar-nav">
            
            <% if user_signed_in? %>   
              <li><%= link_to "All Rents", rents_path %></li>  
              <li><%= link_to "All Products", products_path %></li>
            <% end %>

            <% if user_signed_in? && current_user.role.name == 'admin'%>
              <li><%= link_to "All Users", users_list_path %></li>
            <% end %>           
            
         </ul>   
         <ul class="nav navbar-nav navbar-right">   
            <% if user_signed_in? %>  
            <li><%= link_to current_user.email, edit_user_registration_path %></li> 
            <%= link_to "Log out" , destroy_user_session_path, method: :delete, :class => "btn btn-danger navbar-btn" %>
            <% else %>   
            <li><%= link_to "Sign In", user_session_path %></li>   
            <li><%= link_to "Register", new_user_registration_path %></li>   
            <% end %>   
         </ul>   
       </div>   
    </div>   
    <div class="container">   
       <% flash.each do |type, message| %>   
       <div class="alert <%= flash_class type %> alert-dismissable">   
         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>   
         <p><%= message %></p>   
       </div>   
       <% end %>   
       <%= yield %>   
    </div>   
  </body>   
  </html>   